controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    torso_controller:
      type: position_controllers/JointGroupPositionController

    head_controller:
      type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

torso_controller:
  ros__parameters:
    joints:
      - j1_torso
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      - effort

head_controller:
  ros__parameters:
    joints:
      - j1_head
      - j2_head
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      - effort
