waypoint_navigation:
  waypoint_navigation_node:
    ros__parameters:
      wps:
        - "1"
        - "1.84"
        - "1.34"
        - "-0.03"
        - "1.0"

        - "bathroom"
        - "5.0"
        - "3.68"
        - "0.81"
        - "0.59"

        - "3"
        - "7.34"
        - "6.45"
        - "0.99"
        - "0.12"

        - "4"
        - "1.25"
        - "9.40"
        - "-0.78"
        - "0.67"

        - "entrance"
        - "1.25"
        - "6.30"
        - "-0.78"
        - "0.67"

        - "livingroom"
        - "1.55"
        - "4.03"
        - "-0.69"
        - "0.72"

        - "7"
        - "4.89"
        - "1.64"
        - "0.01"
        - "1.0"

        - "8"
        - "6.80"
        - "1.56"
        - "0.53"
        - "0.85"

        - "bedroom"
        - "7.50"
        - "4.89"
        - "0.76"
        - "0.65"

        - "kitchen"
        - "3.79"
        - "6.77"
        - "0.99"
        - "0.12"
